definitions:
  models.User:
    properties:
      email:
        example: josuel@example.com
        type: string
      id:
        example: 507f1f77bcf86cd799439011
        type: string
      name:
        example: Josuel
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      description: Retorna todos os usuários cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Erro interno
          schema:
            type: string
      summary: Lista usuários
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Cria um novo usuário com nome e e-mail
      parameters:
      - description: Usuário a ser criado
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Erro ao criar usuário
          schema:
            type: string
      summary: Cria usuário
      tags:
      - users
swagger: "2.0"
