name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout o código
      uses: actions/checkout@v4

    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Instalar dependências
      run: go mod tidy

    - name: Instalar swaggo/swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Gerar documentação Swagger
      run: swag init

    - name: Build do projeto
      run: go build -v ./...

    - name: Rodar testes
      run: go test -v ./tests

    - name: Verificar se documentação foi gerada
      run: test -f ./docs/docs.go
